version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - DEBUG=True
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
