services:
  - type: web
    name: utdrs-api-gateway
    env: docker
    repo: https://github.com/yourusername/utdrs-api-gateway.git  # Update with your repo
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MONGODB_URI
        sync: false  # Set this manually in the Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: DEBUG
        value: false
